# -*- coding: utf-8 -*-
"""exam25_matplotlib_visualization01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19gVArAlnI1IpQ4UlYieGOlvudfBTGd8H
"""

import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
plt.rcParams['figure.dpi'] = 70

fig = plt.figure(figsize=(8, 5))
ax = fig.add_axes([0, 0, 1, 1])
ax.set_title('figure')
plt.show()

x = [0, 1]
y = [0, 1]
fig = plt.figure(figsize=(8, 5))
ax = [None, None, None]
ax[0] = fig.add_axes([0.1, 0.1, 0.4, 0.8])
ax[1] = fig.add_axes([0.55, 0.15, 0.35, 0.4])
ax[2] = fig.add_axes([0.65, 0.6, 0.2, 0.3])
ax[1].plot(x, y)
for i in range(3):
    ax[i].set_title('ax[{}]'.format(i))
    ax[i].set_xticks([])
    ax[i].set_yticks([])
plt.show()

fig, axes = plt.subplots()
axes.plot(x, y)
plt.show()

fig, axes = plt.subplots(2, 3, figsize=(8, 5))
axes[0, 1].plot(x, y)
plt.tight_layout()
plt.show()

fig, axes = plt.subplots()
axin1 = axes.inset_axes([0.8, 0.1, 0.15, 0.15], xticks=[], yticks=[])
plt.show()

fig = plt.figure(figsize=(8, 5))
axes = []
axes.append(plt.subplot2grid((2, 3), (0,0)))
# axes.append(plt.subplot2grid((2, 3), (0,1)))
axes.append(plt.subplot2grid((2, 3), (0,2)))
# axes.append(plt.subplot2grid((2, 3), (1,0)))
axes.append(plt.subplot2grid((2, 3), (1,1)))
# axes.append(plt.subplot2grid((2, 3), (1,2)))

plt.show()

fig = plt.figure(figsize=(8, 5))
axes = []
axes.append(plt.subplot2grid((3, 4), (0, 0), colspan=2, rowspan=2))
axes.append(plt.subplot2grid((3, 4), (0, 2)))
axes.append(plt.subplot2grid((3, 4), (0, 3), rowspan=3))
axes.append(plt.subplot2grid((3, 4), (1, 2)))
axes.append(plt.subplot2grid((3, 4), (2, 0), colspan=3))
for i in range(5):
    axes[i].set_title('axes[{}]'.format(i))
    axes[i].set_xticks([])
    axes[i].set_yticks([])
fig.tight_layout(pad=2)
plt.show()

from mpl_toolkits.axes_grid1 import axes_divider
from mpl_toolkits.axes_grid1.axes_divider import make_axes_locatable

fig, axes = plt.subplots()
ax_divider = make_axes_locatable(axes)
axes = ax_divider.append_axes('right', size='10%', pad='5%', xticks=[], yticks=[])
plt.show()

